Handle tokens that do not report a serial number
frankmorgner/OpenSCToken pull request #10
Opened 2019-06-24 12:08 UTC by michaelweiser

At least one specific implementation of CardOS5 cards does not seem to
report a serial number which makes OpenSCToken terminate with:

OpenSCToken: (CoreFoundation) *** Terminating app due to uncaught
exception 'NSInvalidArgumentException', reason: '*** +[NSString
stringWithUTF8String:]: NULL cString'

This change makes OpenSCToken work for these cards as well.

2019-06-24 14:11 UTC, frankmorgner requested changes
thanks, looks good. However, please add the following check:

```
if (p15card->tokeninfo != NULL && p15card->tokeninfo->serial_number != NULL)
```

2019-06-24 14:42 UTC, michaelweiser commented
> thanks, looks good. However, please add the following check:
> 
> ```
> if (p15card->tokeninfo != NULL && p15card->tokeninfo->serial_number != NULL)
> ```

Done plus explanatory comment.

2019-06-24 15:00 UTC, merged

2019-06-24 15:00 UTC, frankmorgner commented
thanks

2019-09-13 15:21 UTC, akemnade commented
is related to

https://github.com/OpenSC/OpenSC/pull/1791